### ISSUE TITLE
[UHN-BS-11] Get a Start on Data Metrics 

### ISSUE THREAD

**Issue by Asiapenguin** [CodetheChangeFoundation/UHN-Backend-Server#25]
- [List of Metrics](https://docs.google.com/document/d/1qeaz-KIytLtqVz_8NLF1tZxQM0uRigZukGRdXGn4CYA/edit?usp=sharing)
- Focus on numbers 1 - 3 for this task
  - You want to first dumb down each metric to very simple counts. We dont need to combine the raw data ourselves. We just need to make sure that from the raw data that we collect, these metrics can be analyzed from it.
- Come up with a database schema for what you think will be needed for these 3 points and the points that follow (extensibility)
  - Put into Google Doc and review with @Asiapenguin and @angadkalra 
- Setup Postgres Database for this
- Inject some code into relevant places to populate this database

**Comment by andrchoi** [comment]
Draft database schema available for review:

https://docs.google.com/document/d/1sb4nOgnWdAycwdQwjx_XBPrRWrhHdCQKQPAANvLOsdc/edit
