### ISSUE TITLE
[UHN-BS-24] DELETE /users/{id}/responders

### ISSUE THREAD

**Issue by Asiapenguin** [CodetheChangeFoundation/UHN-Backend-Server#47]
***NOTE: wait for @mxnyee to test whether DELETE supports this on axios

- Change the current DELETE to batch delete:
  - Similar to POST /users/{id}/responders but for DELETE operation
  - respondersToDelete instead of respondersToAdd

**Comment by mxnyee** [comment]
Seems to work just fine with axios.
The DELETE request will come in with data in req.body as usual.

**Comment by Asiapenguin** [comment]
@matthewleemle go ahead with expecting the to-be-deleted ids to be in the request body

**Comment by matthewleemle** [comment]
> @matthewleemle go ahead with expecting the to-be-deleted ids to be in the request body

Acknowledged
