### ISSUE TITLE
[UHN-BS-26] Add Responders endpoint fails for multiple responders

### ISSUE THREAD

**Issue by mxnyee** [CodetheChangeFoundation/UHN-Backend-Server#50]
This only happens sometimes.
The POST /users/:id/responders endpoint will fail to add all user ids sent in the request body.
To reproduce:
- hit the POST /users/:id/responders endpoint and give more than one user id in the body
- then, view that user's responders by hitting GET /users/:id/responders (or just looking in the mongo db)
- result: occasionally, not all of the responders were added to that user's profile
- expected result: all of the responders should have been added to that user's profile

Looks like the problem is in addResponders at Controllers/user.js:214.
The backend server spits out this error:
![UHN-BS-26.jpg](https://images.zenhubusercontent.com/5d8534e2db42c800012543f2/83ed6870-dec8-4150-bdf6-323f24c290de)

**Comment by Asiapenguin** [comment]
@matthewleemle Can you please take a look at this?

**Comment by matthewleemle** [comment]
@mxnyee Can I see an example of a post request you are sending?

**Comment by mxnyee** [comment]
![image](https://user-images.githubusercontent.com/42985875/74198867-6e7f0b80-4c17-11ea-9e37-376bba5a4cc0.png)
